#include "definitions.h"
const U64 NOT_A_FILE = 0xFEFEFEFEFEFEFEFEULL;
const U64 NOT_H_FILE = 0xFEFEFEFEFEFEFEFEULL;
const U64 NOT_HG_FILE= 0x3F3F3F3F3F3F3F3FULL;
const U64 NOT_AB_FILE= 0xFCFCFCFCFCFCFCFCULL;